### ISSUE TITLE
Add a dictionary to verify word validity

### ISSUE THREAD

**Issue by MKolman** [NejcKolman/multiplayer-wordle#12]
Add both slovenian and english dictionaries so that words entered can be verified as valid.

**Comment by MKolman** [comment]
Hint:
Save the dictionaries in e.g. `data/words/en.txt` and `data/words/sl.txt` with one word per line.
Then you can fetch these using `fetch` function:
```javascript
let ALL_WORDS = []
async function fetchWords(language) {
    let response = await fetch("data/words/" + language + ".txt")
    let words = await response.text()
    ALL_WORDS = words.split('\n')
}
fetchWords('en')
```

**Comment by NejcKolman** [comment]
resolved
