### ISSUE TITLE
Add ability to share your score

### ISSUE THREAD

**Issue by MKolman** [NejcKolman/multiplayer-wordle#13]
Sharing your achievements is a big part of the appeal of the original game. Add a share button where users can share their score with others. To do that you have to see if their device supports sharing (mostly only supported by mobile browsers) and then use the sharing API.

See how to use javascript sharing and which browsers support it:
https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share

**Comment by NejcKolman** [comment]
copy score in added
