### ISSUE TITLE
Set up a better project structure

### ISSUE THREAD

**Issue by MKolman** [NejcKolman/multiplayer-wordle#4]
Currently the project files are all a big mess in the root of the directory. I suggest creating a better directory structure and filenames to reflect the project functionality.

1. Remove all unneeded html files. For now you only need one to select the word and one to play wordle on. There's no sense in pre-creating files for future pages.
2. Rename current files according to convention.
    * The landing page (the first page you want to load when visiting your website) should be  called `index.html`. Index is a special name that is auto loaded when no file is specified in the URL (https://www.kolman.si actually loads https://www.kolman.si/index.html )
    * The second page should have a short and descriptive name (e.g. play.html or guess.html)
3. Create folders for static files (img, css, js). Since git does not allow empty folders, I suggest adding an empty file called `.gitkeep` in each of those folders.

**Comment by NejcKolman** [comment]
I think this is done
