### ISSUE TITLE
Encrypt the word in the URL so it's not recognizable when sharing a link

### ISSUE THREAD

**Issue by MKolman** [NejcKolman/multiplayer-wordle#6]
Currently the sharing link includes the word you will be trying to guess. This will immediately spoil the game for anyone playing. The word in the URL has to be obfuscated so it's not recognizable.

The simplest solution for this is to use Base64 encoding. JavaScript supports this with functions `atob` and `btoa` as follows:
```
btoa("guess")  # returns 'Z3Vlc3M='
atob("Z3Vlc3M=")  # returns 'guess'
```

So simply call `btoa` before creating URL and call `atob` after reading the word from the URL.

**Comment by NejcKolman** [comment]
Encripted finnished
